FROM node:12-alpine

LABEL "repository"="https://github.com/matthewlehner/actions"
LABEL "homepage"="https://github.com/matthewlehner/actions/node"
LABEL "maintainer"="Matthew Lehner <matthew@mpl.io>"

LABEL "com.github.actions.name"="Node 12.x"
LABEL "com.github.actions.description"="An action for running Node commands"
LABEL "com.github.actions.icon"="code"
LABEL "com.github.actions.color"="green"